[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#f43c34"

# Background color for the main content area.
backgroundColor = "#F3F5F7"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#dcdee3"

# Color used for almost all text.
textColor = "#1f4747"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "monospace" 